### ISSUE TITLE
Question about mesh visualization

### ISSUE THREAD

**Issue by Nottoday23** [rolpotamias/WiLoR#15]
Hi,  thank you for the fantastic work on WiLoR. When using renderer.vertices_to_trimesh to generate a hand mesh for visualization with trimesh, the resulting mesh cannot be visualized as expected. 

I ran the command trimesh.Scene(tmesh).show() and encountered the following error:
Traceback (most recent call last):
  File "/home/usr/.conda/envs/wilor/lib/python3.10/site-packages/pyglet/graphics/__init__.py", line 450, in _get_domain
    domain = domain_map[key]
KeyError: (('v3f/static', 'n3f/static', 'c4B/static'), 4, True)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/usr/code/WiLoR/demo.py", line 155, in <module>
    main()
  File "/home/usr/code/WiLoR/demo.py", line 110, in main
    trimesh.Scene(tmesh).show()
  File "/home/usr/.conda/envs/wilor/lib/python3.10/site-packages/trimesh/scene/scene.py", line 1394, in show
    return SceneViewer(self, **kwargs)
  File "/home/usr/.conda/envs/wilor/lib/python3.10/site-packages/trimesh/viewer/windowed.py", line 203, in __init__
    self._update_vertex_list()
  File "/home/usr/.conda/envs/wilor/lib/python3.10/site-packages/trimesh/viewer/windowed.py", line 235, in _update_vertex_list
    self.add_geometry(name=name, geometry=geom, smooth=bool(self._smooth))
  File "/home/usr/.conda/envs/wilor/lib/python3.10/site-packages/trimesh/viewer/windowed.py", line 265, in add_geometry
    self.vertex_list[name] = self.batch.add_indexed(*args)
  File "/home/usr/.conda/envs/wilor/lib/python3.10/site-packages/pyglet/graphics/__init__.py", line 396, in add_indexed
    domain = self._get_domain(True, mode, group, formats)
  File "/home/usr/.conda/envs/wilor/lib/python3.10/site-packages/pyglet/graphics/__init__.py", line 454, in _get_domain
    domain = vertexdomain.create_indexed_domain(*formats)
  File "/home/usr/.conda/envs/wilor/lib/python3.10/site-packages/pyglet/graphics/vertexdomain.py", line 146, in create_indexed_domain
    return IndexedVertexDomain(attribute_usages)
  File "/home/usr/.conda/envs/wilor/lib/python3.10/site-packages/pyglet/graphics/vertexdomain.py", line 620, in __init__
    super(IndexedVertexDomain, self).__init__(attribute_usages)
  File "/home/usr/.conda/envs/wilor/lib/python3.10/site-packages/pyglet/graphics/vertexdomain.py", line 194, in __init__
    buffer = vertexbuffer.create_mappable_buffer(
  File "/home/usr/.conda/envs/wilor/lib/python3.10/site-packages/pyglet/graphics/vertexbuffer.py", line 110, in create_mappable_buffer
    return MappableVertexBufferObject(size, target, usage)
  File "/home/usr/.conda/envs/wilor/lib/python3.10/site-packages/pyglet/graphics/vertexbuffer.py", line 384, in __init__
    super(MappableVertexBufferObject, self).__init__(size, target, usage)
  File "/home/usr/.conda/envs/wilor/lib/python3.10/site-packages/pyglet/graphics/vertexbuffer.py", line 301, in __init__
    glPushClientAttrib(GL_CLIENT_VERTEX_ARRAY_BIT)
  File "/home/usr/.conda/envs/wilor/lib/python3.10/site-packages/pyglet/gl/lib.py", line 107, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid operation'
Exception ignored in: <function VertexDomain.__del__ at 0x7f5830abf640>
Traceback (most recent call last):
  File "/home/usr/.conda/envs/wilor/lib/python3.10/site-packages/pyglet/graphics/vertexdomain.py", line 232, in __del__
    for attribute in self.attributes:
AttributeError: 'IndexedVertexDomain' object has no attribute 'attributes'

Looking forward to your reply.

**Comment by rolpotamias** [comment]
I am assuming that there is something wrong in your trimesh/pyglet installation. 

Maybe you can try directly using tmesh.show() or even better try to export the mesh tmesh.export('your_path.obj') and visualize it in another software like [Meshlab](https://www.meshlab.net/) or [Blender](https://www.blender.org/download/).
