### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by helloyujiaxu** [rolpotamias/WiLoR#3]
(I am not an English user and my English is not good. The following content was obtained using translation software.)
First of all, thank you for creating this unparalleled project.
I have some questions about this project, but I want to run the demo first. This may be a slightly foolish question, but I really can't solve it.
The following is the error message:

```
Traceback (most recent call last):
  File "/home/daisy/coding/WiLoR/demo.py", line 128, in <module>
    main()
  File "/home/daisy/coding/WiLoR/demo.py", line 28, in main
    model, model_cfg = load_wilor(checkpoint_path = './pretrained_models/wilor_final.ckpt' , cfg_path= './pretrained_models/model_config.yaml')
  File "/home/daisy/coding/WiLoR/wilor/models/__init__.py", line 35, in load_wilor
    model = WiLoR.load_from_checkpoint(checkpoint_path, strict=False, cfg=model_cfg)
  File "/home/daisy/miniconda3/envs/wilor/lib/python3.10/site-packages/pytorch_lightning/utilities/model_helpers.py", line 125, in wrapper
    return self.method(cls, *args, **kwargs)
  File "/home/daisy/miniconda3/envs/wilor/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1582, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/home/daisy/miniconda3/envs/wilor/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 91, in _load_from_checkpoint
    model = _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/home/daisy/miniconda3/envs/wilor/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 165, in _load_state
    obj = instantiator(cls, _cls_kwargs) if instantiator else cls(**_cls_kwargs)
  File "/home/daisy/coding/WiLoR/wilor/models/wilor.py", line 52, in __init__
    self.mano = MANO(**mano_cfg)
  File "/home/daisy/coding/WiLoR/wilor/models/mano_wrapper.py", line 19, in __init__
    super(MANO, self).__init__(*args, **kwargs)
  File "/home/daisy/miniconda3/envs/wilor/lib/python3.10/site-packages/smplx/body_models.py", line 1704, in __init__
    super(MANOLayer, self).__init__(
  File "/home/daisy/miniconda3/envs/wilor/lib/python3.10/site-packages/smplx/body_models.py", line 1557, in __init__
    assert osp.exists(mano_path), 'Path {} does not exist!'.format(
AssertionError: Path ./mano_data/MANO_RIGHT.pkl does not exist!
```

It prompted me that the file 'MANO-RIGHT.pkl' is missing, but I couldn't find it in the files I downloaded from Git or in the file list on GitHub.
I am looking forward to your reply.

**Comment by rolpotamias** [comment]
You are required to download MANO model from [MANO website](https://mano.is.tue.mpg.de/). Create an account by clicking Sign Up and download the models (mano_v*_*.zip). Unzip and place the right hand model MANO_RIGHT.pkl under the mano_data/ folder.

**Comment by helloyujiaxu** [comment]
Thank you for your guidance, I successfully ran the demo!
Do I need to close this issue now?
