### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Uniky** [rolpotamias/WiLoR#4]
python gradio_demo.py
Loading  ./pretrained_models/wilor_final.ckpt
Lightning automatically upgraded your loaded checkpoint from v1.8.1 to v2.4.0. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint pretrained_models/wilor_final.ckpt`
WARNING: You are using a MANO model, with only 10 shape coefficients.
libEGL warning: MESA-LOADER: failed to open vgem: /usr/lib/dri/vgem_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)

libEGL warning: NEEDS EXTENSION: falling back to kms_swrast
libEGL warning: MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)

Traceback (most recent call last):
  File "/mnt/h/AI/3D/WiLoR/gradio_demo.py", line 27, in <module>
    model, model_cfg = load_wilor(checkpoint_path = './pretrained_models/wilor_final.ckpt' , cfg_path= './pretrained_models/model_config.yaml')
  File "/mnt/h/AI/3D/WiLoR/wilor/models/__init__.py", line 35, in load_wilor
    model = WiLoR.load_from_checkpoint(checkpoint_path, strict=False, cfg=model_cfg)
  File "/mnt/h/ai/3d/WiLoR/venv_linux/lib/python3.10/site-packages/pytorch_lightning/utilities/model_helpers.py", line 125, in wrapper
    return self.method(cls, *args, **kwargs)
  File "/mnt/h/ai/3d/WiLoR/venv_linux/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1582, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/mnt/h/ai/3d/WiLoR/venv_linux/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 91, in _load_from_checkpoint
    model = _load_state(cls, checkpoint, strict=strict, **kwargs)
  File "/mnt/h/ai/3d/WiLoR/venv_linux/lib/python3.10/site-packages/pytorch_lightning/core/saving.py", line 165, in _load_state
    obj = instantiator(cls, _cls_kwargs) if instantiator else cls(**_cls_kwargs)
  File "/mnt/h/AI/3D/WiLoR/wilor/models/wilor.py", line 59, in __init__
    self.mesh_renderer = MeshRenderer(self.cfg, faces=self.mano.faces)
  File "/mnt/h/AI/3D/WiLoR/wilor/utils/mesh_renderer.py", line 49, in __init__
    self.renderer = pyrender.OffscreenRenderer(viewport_width=self.img_res,
  File "/mnt/h/ai/3d/WiLoR/venv_linux/lib/python3.10/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/mnt/h/ai/3d/WiLoR/venv_linux/lib/python3.10/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/mnt/h/ai/3d/WiLoR/venv_linux/lib/python3.10/site-packages/pyrender/platforms/egl.py", line 177, in init_context
    assert eglInitialize(self._egl_display, major, minor)
  File "/mnt/h/ai/3d/WiLoR/venv_linux/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/mnt/h/ai/3d/WiLoR/venv_linux/lib/python3.10/site-packages/OpenGL/error.py", line 228, in glCheckError
    raise GLError(
OpenGL.error.GLError: GLError(
        err = 12289,
        baseOperation = eglInitialize,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7fda2f57c6c0>,
                c_long(0),
                c_long(0),
        ),
        result = 0
)

**Comment by Uniky** [comment]
It seems the env created by conda has some issues, switching to Pyenv solves the problem
